//Different datatypes for WSR frontend, based on the data received from backend via GET requests. 
//Fields that are generated by backend after creation (id, timecreated, timeupdated, etc) are designated with a '?' so they can be undefined for when we are constructing a new object to be created by the backend

// Parent interface that defines common properties shared by all other interfaces in this file.
// These properties include universally applicable fields such as 'id', 'time_created', and 'time_updated'.
export interface ResourceWithMetadata{
    id?: number;
    time_created?: string;
    time_updated?: string;
};

export interface Stock extends ResourceWithMetadata{
    ticker: string;
    trade_price: number;
};

export interface Holdings extends ResourceWithMetadata{
    stock: number; //numerical id of associated stock
    stock_data: Stock;
    shares: number;
    total_value: number;
};

export interface Portfolio extends ResourceWithMetadata{
    holdings: Holdings[];
    cash: number;
};