# Generated by Django 5.1.3 on 2024-11-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='trade_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
