# Generated by Django 5.1.4 on 2025-01-09 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_summary', models.BooleanField(default=True)),
                ('daily_summary', models.BooleanField(default=False)),
                ('contest_rank_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='player',
            name='alert_preferences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app.alertpreferences'),
        ),
    ]
