# Generated by Django 5.1.4 on 2025-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='nasdaq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='nyse',
            field=models.BooleanField(default=False),
        ),
    ]
