# Generated by Django 5.1.4 on 2025-01-14 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contest_crypto_contest_nasdaq_contest_nyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='app.contest'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
