# Generated by Django 5.1.4 on 2025-01-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_portfolio_contest_alter_portfolio_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_datetime',
            field=models.DateField(),
        ),
    ]
