# Generated by Django 5.1.4 on 2025-01-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contest_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='start_datetime',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=10),
        ),
    ]
