# Generated by Django 5.1.4 on 2025-01-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_end_datetime_contest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
