# Generated by Django 5.1.4 on 2025-01-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_portfolio_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='crypto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='nasdaq',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='nyse',
            field=models.BooleanField(default=True),
        ),
    ]
