# Generated by Django 5.1.4 on 2025-01-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contest_crypto_alter_contest_nasdaq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default='Contest Name', max_length=50),
            preserve_default=False,
        ),
    ]
