# Generated by Django 5.1.4 on 2025-01-16 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(default='Denver', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='education',
            field=models.CharField(choices=[('None', 'None'), ('High School', 'High School'), ('College', 'College'), ('Post-Grad', 'Post-Grad')], default='None', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('None', 'None'), ('High School', 'High School'), ('College', 'College'), ('Post-Grad', 'Post-Grad')], default='Male', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='here_for_the',
            field=models.CharField(choices=[('Competition', 'Competition'), ('Cash Prizes', 'Cash Prizes'), ('Learning', 'Learning'), ('Strategy Testing', 'Strategy Testing'), ('Just Checking It Out', 'Just Checking It Out')], default='Competition', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(default='CO', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertpreferences',
            name='daily_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertpreferences',
            name='weekly_summary',
            field=models.BooleanField(default=False),
        ),
    ]
