# Generated by Django 5.1.5 on 2025-01-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_player_investing_knowledge_alter_player_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.CharField(default='Denver, CO', max_length=255),
            preserve_default=False,
        ),
    ]
