# Generated by Django 5.1.5 on 2025-01-22 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_player_city_remove_player_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('here_for_the', models.CharField(choices=[('Competition', 'Competition'), ('Cash Prizes', 'Cash Prizes'), ('Learning', 'Learning'), ('Strategy Testing', 'Strategy Testing'), ('Just Checking It Out', 'Just Checking It Out')], default='Competition', max_length=127)),
                ('education', models.CharField(choices=[('None', 'None'), ('High School', 'High School'), ('College', 'College'), ('Post-Grad', 'Post-Grad')], default='None', max_length=127)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=127)),
                ('investing_knowledge', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=127)),
                ('birthday', models.DateField()),
                ('weekly_summary', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=True)),
                ('contest_rank_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='alert_preferences',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='player',
            name='education',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='player',
            name='here_for_the',
        ),
        migrations.RemoveField(
            model_name='player',
            name='investing_knowledge',
        ),
        migrations.AddField(
            model_name='player',
            name='account_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app.accountsettings'),
        ),
        migrations.DeleteModel(
            name='AlertPreferences',
        ),
    ]
