# Generated by Django 5.1.5 on 2025-01-22 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_accountsettings_remove_player_alert_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='account_settings',
        ),
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='contest_rank_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='daily_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='education',
            field=models.CharField(choices=[('None', 'None'), ('High School', 'High School'), ('College', 'College'), ('Post-Grad', 'Post-Grad')], default='None', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='here_for_the',
            field=models.CharField(choices=[('Competition', 'Competition'), ('Cash Prizes', 'Cash Prizes'), ('Learning', 'Learning'), ('Strategy Testing', 'Strategy Testing'), ('Just Checking It Out', 'Just Checking It Out')], default='Competition', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='investing_knowledge',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=127),
        ),
        migrations.AddField(
            model_name='player',
            name='weekly_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
    ]
