# Generated by Django 5.1.5 on 2025-01-22 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_player_account_settings_player_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(default=datetime.date(2005, 1, 27)),
        ),
    ]
