# Generated by Django 5.1.5 on 2025-01-22 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_player_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contest_invite',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('weekly_summary', 'Weekly Summary'), ('daily_summary', 'Daily Summary'), ('Contest Rank Change', 'contest_rank_change'), ('contest_invite', 'Contest Invite')], max_length=127)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='app.contest')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
